spring:
  cloud:
    gateway:
      routes:
        - id: transactions_route
          uri: http://localhost:8080/accounts/{accountId}/transactions
          predicates:
            - Path=/accounts/{accountId}/transactions/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG