spring:
  cloud:
    gateway:
      routes:
        - id: root-redirect
          uri: http://localhost:8080/accounts/123/transactions
          predicates:
            - Path=/
          filters:
            - RewritePath=/, /accounts/123/transactions
